name: yaml-image-updater
description: An action to update all valuefiles for a repo so as to empower a continuous deployment
inputs:
  target-path:
    description: Path to YAML files directory
    required: true
  dispatched-payload:
    description: Payload with image information (JSON)
    required: true
  github-token:
    description: The token to use for github
    required: false
outputs:
  updated-services:
    description: The services that have been updated
  success:
    description: Whether the action was successful
  branch-suffix:
    description: Unique identifier for a branch to be created
  updated-by-repo:
    description: The repo that triggered the update
  updated-by-commit:
    description: The commit that triggered the update
runs:
  using: node20
  main: index.js